" Basic settings
syntax on
set nu
set relativenumber
set cindent
set smartindent
set autoindent
set tabstop=4
set nobackup
set ruler


" Shortcuts
let mapleader=" "

inoremap jk <esc>

nmap <Leader>t :terminal<CR>

